# Generated by Django 3.2.7 on 2021-09-09 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_id', models.PositiveSmallIntegerField(verbose_name='Airplane ID')),
                ('passengers_count', models.PositiveSmallIntegerField(default=0, verbose_name='Number of passengers')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp added to track record creation date')),
                ('added_by', models.ForeignKey(blank=True, help_text='User id saved to track if an authenticated user submits request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
